# Generated by Django 5.2.2 on 2025-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='location',
        ),
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, choices=[('Arnprior Rental Income (MAIN)', 'Arnprior Rental Income (MAIN)'), ('Arnprior Rental Income (LOFT)', 'Arnprior Rental Income (LOFT)'), ('Employment Income', 'Employment Income'), ('Investment Income', 'Investment Income')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='taxable',
            field=models.BooleanField(default=True),
        ),
    ]
