# Generated by Django 5.2.2 on 2025-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bankaccount_expense_bank_account_income_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number_masked',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_number_last4',
            field=models.CharField(blank=True, help_text='Optional: last 4 digits for easier identification.', max_length=4),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
