# Generated by Django 5.2.2 on 2025-11-29 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bankaccount_account_number_masked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('earliest_date', models.DateField()),
                ('latest_date', models.DateField()),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_income_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_expense_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='home.bankaccount')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='home.importbatch'),
        ),
        migrations.AddField(
            model_name='income',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='home.importbatch'),
        ),
    ]
