# Generated by Django 5.2.2 on 2025-11-29 16:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_importbatch_expense_import_batch_income_import_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CHEQUING', 'Chequing'), ('CREDIT_CARD', 'Credit card'), ('SAVINGS', 'Savings'), ('TFSA', 'TFSA'), ('RETIREMENT', 'Retirement (RRSP, etc.)'), ('OTHER', 'Other')], default='CHEQUING', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Latest known bank balance for this account.', max_digits=12),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_withholding_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WithholdingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Desired balance for this bucket (e.g. yearly bill amount).', max_digits=12)),
                ('next_due_date', models.DateField(blank=True, help_text='When the related bill/tax is next due, if known.', null=True)),
                ('account', models.ForeignKey(limit_choices_to={'is_withholding_account': True}, on_delete=django.db.models.deletion.CASCADE, related_name='withholding_categories', to='home.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WithholdingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.withholdingcategory')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
