# Generated by Django 5.2.2 on 2025-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bankaccount_account_type_bankaccount_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, choices=[('Arnprior Rental Income (MAIN)', 'Arnprior Rental Income (MAIN)'), ('Arnprior Rental Income (LOFT)', 'Arnprior Rental Income (LOFT)'), ('Employment Income', 'Employment Income'), ('Investment Income', 'Investment Income'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
