# Generated by Django 5.2.2 on 2025-12-24 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_income_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected monthly income for this category (used for progress bars).', max_digits=10)),
                ('taxable_default', models.BooleanField(default=True, help_text='Default taxable setting for new income entries in this category.')),
            ],
        ),
    ]
