# Generated by Django 5.2.2 on 2025-12-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_incomecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='home.incomecategory'),
        ),
    ]
