# Generated by Django 5.2.2 on 2025-12-24 21:13

from django.db import migrations

def forwards(apps, schema_editor):
    Income = apps.get_model("home", "Income")
    IncomeCategory = apps.get_model("home", "IncomeCategory")

    # Create categories based on existing legacy string values
    legacy_values = (
        Income.objects.exclude(category__isnull=True)
        .exclude(category__exact="")
        .values_list("category", flat=True)
        .distinct()
    )

    name_to_obj = {}
    for name in legacy_values:
        obj, _ = IncomeCategory.objects.get_or_create(name=name)
        name_to_obj[name] = obj

    # Link each Income row to its corresponding IncomeCategory
    for income in Income.objects.all().only("id", "category", "income_category_id"):
        if income.income_category_id:
            continue
        if not income.category:
            continue
        cat = name_to_obj.get(income.category)
        if cat:
            income.income_category_id = cat.id
            income.save(update_fields=["income_category"])


def backwards(apps, schema_editor):
    Income = apps.get_model("home", "Income")
    # On rollback, just clear the FK (legacy string remains)
    Income.objects.update(income_category=None)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_income_income_category'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]