# Generated by Django 5.2.2 on 2025-12-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_rental_business_use_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecategory',
            name='default_rental_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_income_categories', to='home.rentalunit'),
        ),
    ]
