# Generated by Django 5.2.2 on 2026-02-01 14:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_incomecategory_default_rental_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short label, e.g. 'Scotia 5yr fixed' or 'TD Arnprior Mortgage'.", max_length=100)),
                ('lender_name', models.CharField(blank=True, default='', help_text='Optional: lender name (e.g. Scotiabank, TD).', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck if this mortgage has been fully paid off or refinanced.')),
                ('original_principal', models.DecimalField(blank=True, decimal_places=2, help_text='Mortgage amount at origination (optional but recommended).', max_digits=12, null=True)),
                ('origination_date', models.DateField(blank=True, help_text='Date the mortgage originally started.', null=True)),
                ('tracking_start_principal', models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding principal when you started tracking in this app. Typically this should match your lender balance on the tracking start date.', max_digits=12, null=True)),
                ('tracking_start_date', models.DateField(blank=True, help_text='Date that the tracking_start_principal corresponds to.', null=True)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional tweak to reconcile against lender balance if there are small differences. Applied as: current = tracked - principal_paid + adjustment.', max_digits=12)),
                ('amortization_years_total', models.PositiveSmallIntegerField(blank=True, help_text='Total amortization in years (e.g. 25).', null=True)),
                ('amortization_months_extra', models.PositiveSmallIntegerField(default=0, help_text='Extra months beyond whole years in the amortization (e.g. 6 for 25.5 years).')),
                ('amortization_start_date', models.DateField(blank=True, help_text='Start date for the amortization schedule (often the origination date).', null=True)),
                ('payment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Biweekly'), ('ACCEL_BIWEEKLY', 'Accelerated biweekly'), ('WEEKLY', 'Weekly')], default='MONTHLY', help_text='How often regular payments are made.', max_length=20)),
                ('regular_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Contractual payment amount (principal + interest) per payment.', max_digits=12, null=True)),
                ('interest_rate_percent', models.DecimalField(blank=True, decimal_places=3, help_text='Current nominal annual interest rate (e.g. 5.490 means 5.490%).', max_digits=5, null=True)),
                ('compounding_frequency', models.CharField(choices=[('SEMI_ANNUAL', 'Semi-annual (Canadian standard)'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual'), ('OTHER', 'Other / Unknown')], default='OTHER', help_text='Compounding convention (Canadian mortgages are usually semi-annual).', max_length=20)),
                ('interest_rate_effective_date', models.DateField(blank=True, help_text='Date this interest rate took effect (if known).', null=True)),
                ('term_start_date', models.DateField(blank=True, help_text='Start date of the current term.', null=True)),
                ('term_end_date', models.DateField(blank=True, help_text='End date of the current term.', null=True)),
                ('interest_category', models.ForeignKey(blank=True, help_text='Category used for the interest portion of mortgage payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interest_mortgages', to='home.category')),
                ('owned_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to='home.rentalproperty')),
                ('prepayment_category', models.ForeignKey(blank=True, help_text='Optional: category used for extra principal prepayments, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayment_mortgages', to='home.category')),
                ('principal_category', models.ForeignKey(blank=True, help_text='Category used for the principal portion of regular mortgage payments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_mortgages', to='home.category')),
            ],
            options={
                'ordering': ['owned_property__name', 'name'],
            },
        ),
    ]
