# Generated by Django 5.2.2 on 2026-02-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_propertymortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproperty',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated market value for this property.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rentalproperty',
            name='last_valued_date',
            field=models.DateField(blank=True, help_text='Date this estimated value was last updated.', null=True),
        ),
    ]
