# Generated by Django 5.2.2 on 2026-02-01 20:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rentalproperty_estimated_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='withholding_category',
            field=models.ForeignKey(blank=True, help_text='If this expense is funded from a withholding bucket, select it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='home.withholdingcategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='rental_business_use_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional: percent (0–100) of this expense that relates to rental use (useful for mixed-use properties like Foxview).', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount of the transfer.', max_digits=12)),
                ('description', models.CharField(blank=True, default='', help_text="Optional short label (e.g. 'Jenna contribution', 'Move to Arnprior tax bucket').", max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional longer notes about this transfer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, help_text='Account the money is leaving. Leave blank if this is funding from an external source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='home.bankaccount')),
                ('import_batch', models.ForeignKey(blank=True, help_text='Optional: if this transfer came from a CSV import batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='home.importbatch')),
                ('to_account', models.ForeignKey(blank=True, help_text='Account the money is going into. Leave blank if this is going out to an external destination.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='home.bankaccount')),
                ('withholding_category', models.ForeignKey(blank=True, help_text='If this transfer is related to a withholding bucket, select it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='home.withholdingcategory')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
