# Generated by Django 5.2.2 on 2026-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_expense_withholding_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withholdingcategory',
            name='monthly_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Desired monthly contribution into this bucket (e.g. 250.00 for insurance).', max_digits=12, null=True),
        ),
    ]
