# Generated by Django 5.2.2 on 2026-02-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_add_transfer_splits'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transfer',
            name='transfer_split_idx',
        ),
    ]
