# Generated by Django 5.2.2 on 2026-02-21 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_transfer_transfer_split_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthEndClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the closed month (e.g., 2024-01-01 for January 2024)', unique=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.CharField(default='System', max_length=100)),
                ('backup_file', models.CharField(blank=True, help_text='Path to backup file created during close', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_transfers', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=True, help_text='When locked, transactions in this month cannot be edited or deleted')),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_by', models.CharField(blank=True, max_length=100)),
                ('reopen_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Month-End Close',
                'verbose_name_plural': 'Month-End Closes',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_net_worth', models.DecimalField(decimal_places=2, help_text='Total assets minus liabilities', max_digits=12)),
                ('liquid_assets', models.DecimalField(decimal_places=2, default=0, help_text='Cash and easily convertible assets (bank accounts)', max_digits=12)),
                ('investment_assets', models.DecimalField(decimal_places=2, default=0, help_text='Stocks, bonds, retirement accounts', max_digits=12)),
                ('property_value', models.DecimalField(decimal_places=2, default=0, help_text='Real estate and property values', max_digits=12)),
                ('liabilities', models.DecimalField(decimal_places=2, default=0, help_text='Loans, credit cards, mortgages', max_digits=12)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('month_close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshot', to='home.monthendclose')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Account balance at month-end', max_digits=12)),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_snapshots', to='home.bankaccount')),
                ('month_close', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_snapshots', to='home.monthendclose')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('month_close', 'bank_account')},
            },
        ),
    ]
