# Generated by Django 5.2.2 on 2026-02-22 13:44

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_monthendclose_networthsnapshot_accountsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(upload_to=home.models.expense_attachment_upload_to),
        ),
    ]
