# Generated by Django 5.2.2 on 2026-03-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_expense_attachment_naming'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthendclose',
            name='excess_saved',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount saved to Excess/Surplus bucket', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='planned_budget_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total budget for planned expense categories (with monthly_limit)', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='planned_spent_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total spent in planned expense categories', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='unplanned_spent_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total spent in unplanned expense categories (without monthly_limit)', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='withholding_actual_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total contributions to withholding buckets', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthendclose',
            name='withholding_target_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total monthly targets for withholding buckets', max_digits=12),
        ),
    ]
