# Generated by Django 5.2.2 on 2026-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_month_end_enhanced_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic balance updates from transactions.'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance_tracking_start_date',
            field=models.DateField(blank=True, help_text='Only transactions on/after this date will affect the balance.', null=True),
        ),
    ]
