# Generated by Django 5.2.2 on 2026-03-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_add_balance_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the adjustment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Adjustment amount (positive = increase balance, negative = decrease balance)', max_digits=12)),
                ('reason', models.CharField(help_text='Brief reason for adjustment (e.g., "Bank reconciliation")', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional detailed notes about this adjustment')),
                ('created_by', models.CharField(default='System', help_text='User who created this adjustment', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(help_text='Account being adjusted', on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='home.bankaccount')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
