# Generated by Django 5.2.2 on 2026-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_backfill_category_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived categories are hidden from dashboards and dropdowns but preserved in historical data.'),
        ),
    ]
