# Generated by Django 5.2.2 on 2026-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pinned_income_categories',
            field=models.ManyToManyField(blank=True, help_text="Income categories shown on this user's dashboard. Leave empty to show all.", to='home.incomecategory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pinned_withholding_categories',
            field=models.ManyToManyField(blank=True, help_text="Withholding buckets shown on this user's dashboard. Leave empty to show all.", to='home.withholdingcategory'),
        ),
    ]
